unit z3_polynomial;
{ This unit is automatically generated by Chet:
  https://github.com/neslib/Chet }

interface

uses z3;

(**
       \brief Return the nonzero subresultants of \c p and \c q with respect to the "variable" \c x.

       \pre \c p, \c q and \c x are Z3 expressions where \c p and \c q are arithmetic terms.
       Note that, any subterm that cannot be viewed as a polynomial is assumed to be a variable.
       Example: \ccode{f(a)} is a considered to be a variable in the polynomial \ccode{
       f(a)*f(a) + 2*f(a) + 1}

       def_API('Z3_polynomial_subresultants', AST_VECTOR, (_in(CONTEXT), _in(AST), _in(AST), _in(AST)))
 *)
function Z3_polynomial_subresultants(c: Z3_context; p: Z3_ast; q: Z3_ast; x: Z3_ast): Z3_ast_vector; cdecl;
  external z3_dll name 'Z3_polynomial_subresultants';

implementation

end.